//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEgresados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificacione
    {
        public int id_certificacion { get; set; }
        public int id_egresado { get; set; }
        public string nombre { get; set; }
        public string entidad_emisora { get; set; }
        public Nullable<System.DateTime> fecha_emision { get; set; }
    
        public virtual Egresado Egresado { get; set; }
    }
}
