//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEgresados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CVs_Egresados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CVs_Egresados()
        {
            this.Postulaciones = new HashSet<Postulacione>();
            this.Visualizaciones_CV = new HashSet<Visualizaciones_CV>();
        }
    
        public int id_cv { get; set; }
        public int id_egresado { get; set; }
        public string ruta_archivo { get; set; }
        public string nombre_archivo { get; set; }
        public string extension { get; set; }
        public Nullable<long> tamano_archivo { get; set; }
        public Nullable<decimal> experiencia_anos { get; set; }
        public string habilidades_principales { get; set; }
        public string idiomas { get; set; }
        public string certificaciones { get; set; }
        public Nullable<bool> disponible_busqueda { get; set; }
        public string privacidad { get; set; }
        public Nullable<int> veces_visualizado { get; set; }
        public Nullable<System.DateTime> fecha_subida { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
        public string CartaPresentacion { get; set; }
    
        public virtual Egresado Egresado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Postulacione> Postulaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visualizaciones_CV> Visualizaciones_CV { get; set; }
    }
}
