//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEgresados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Egresado_Idiomas
    {
        public int id_eg_idioma { get; set; }
        public int id_egresado { get; set; }
        public int id_idioma { get; set; }
        public string nivel { get; set; }
    
        public virtual Egresado Egresado { get; set; }
        public virtual Idioma Idioma { get; set; }
    }
}
