//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEgresados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.Usuarios_Empresa = new HashSet<Usuarios_Empresa>();
            this.Vacantes = new HashSet<Vacante>();
            this.Visualizaciones_CV = new HashSet<Visualizaciones_CV>();
            this.Puntuaciones_Empresas = new HashSet<Puntuaciones_Empresas>();
        }
    
        public int id_empresa { get; set; }
        public string razon_social { get; set; }
        public string nit { get; set; }
        public string email_contacto { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public string sector_economico { get; set; }
        public string tamano_empresa { get; set; }
        public Nullable<bool> vinculada_universidad { get; set; }
        public Nullable<decimal> puntuacion_empresa { get; set; }
        public Nullable<bool> estado_activo { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios_Empresa> Usuarios_Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacante> Vacantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visualizaciones_CV> Visualizaciones_CV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Puntuaciones_Empresas> Puntuaciones_Empresas { get; set; }
    }
}
