//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEgresados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs_Sistema
    {
        public int id_log { get; set; }
        public string usuario_tipo { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string accion { get; set; }
        public string entidad { get; set; }
        public Nullable<int> id_registro { get; set; }
        public string detalles { get; set; }
        public string ip_address { get; set; }
        public Nullable<System.DateTime> fecha_accion { get; set; }
    }
}
