//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEgresados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificacione
    {
        public int id_notificacion { get; set; }
        public string destinatario_tipo { get; set; }
        public int id_destinatario { get; set; }
        public string titulo { get; set; }
        public string mensaje { get; set; }
        public string tipo { get; set; }
        public Nullable<bool> leida { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
    }
}
