//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEgresados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postulacione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Postulacione()
        {
            this.Respuestas_Postulante = new HashSet<Respuestas_Postulante>();
        }
    
        public int id_postulacion { get; set; }
        public int id_vacante { get; set; }
        public int id_egresado { get; set; }
        public Nullable<int> id_cv { get; set; }
        public Nullable<System.DateTime> fecha_postulacion { get; set; }
        public string estado { get; set; }
        public string motivo_rechazo { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
        public Nullable<bool> fue_contactado { get; set; }
    
        public virtual CVs_Egresados CVs_Egresados { get; set; }
        public virtual Egresado Egresado { get; set; }
        public virtual Vacante Vacante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Respuestas_Postulante> Respuestas_Postulante { get; set; }
    }
}
