//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEgresados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preferencias_Egresado
    {
        public int id_pref { get; set; }
        public int id_egresado { get; set; }
        public Nullable<bool> disponible_inmediata { get; set; }
        public string modalidad_preferida { get; set; }
        public string jornada_preferida { get; set; }
        public string area_interes { get; set; }
        public string ubicacion_preferida { get; set; }
        public Nullable<decimal> salario_min { get; set; }
        public Nullable<decimal> salario_max { get; set; }
        public Nullable<bool> notificar { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
    
        public virtual Egresado Egresado { get; set; }
    }
}
