//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEgresados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preguntas_Vacante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Preguntas_Vacante()
        {
            this.Respuestas_Postulante = new HashSet<Respuestas_Postulante>();
        }
    
        public int id_pregunta_vacante { get; set; }
        public int id_vacante { get; set; }
        public Nullable<int> id_pregunta { get; set; }
        public Nullable<bool> personalizada { get; set; }
        public string texto_personalizado { get; set; }
    
        public virtual Preguntas_Predefinidas Preguntas_Predefinidas { get; set; }
        public virtual Vacante Vacante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Respuestas_Postulante> Respuestas_Postulante { get; set; }
    }
}
