//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEgresados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preguntas_Encuesta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Preguntas_Encuesta()
        {
            this.Respuestas_Encuesta = new HashSet<Respuestas_Encuesta>();
        }
    
        public int id_pregunta_encuesta { get; set; }
        public int id_encuesta { get; set; }
        public string texto_pregunta { get; set; }
        public string tipo { get; set; }
        public Nullable<bool> aplica_si_trabaja { get; set; }
        public Nullable<int> orden { get; set; }
    
        public virtual Encuesta Encuesta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Respuestas_Encuesta> Respuestas_Encuesta { get; set; }
    }
}
