//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEgresados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puntuaciones_Empresas
    {
        public int id_puntuacion { get; set; }
        public Nullable<int> id_Egresado { get; set; }
        public decimal Puntuacion { get; set; }
        public string comentario { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public Nullable<System.DateTime> FechaPuntuacion { get; set; }
    
        public virtual Egresado Egresado { get; set; }
        public virtual Empresa Empresa { get; set; }
    }
}
