//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEgresados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuestas_Encuesta
    {
        public int id_respuesta_encuesta { get; set; }
        public int id_pregunta_encuesta { get; set; }
        public Nullable<int> id_egresado { get; set; }
        public string respuesta { get; set; }
        public Nullable<System.DateTime> fecha_respuesta { get; set; }
    
        public virtual Egresado Egresado { get; set; }
        public virtual Preguntas_Encuesta Preguntas_Encuesta { get; set; }
    }
}
