//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEgresados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuestas_Postulante
    {
        public int id_respuesta { get; set; }
        public int id_postulacion { get; set; }
        public int id_pregunta_vacante { get; set; }
        public string respuesta { get; set; }
    
        public virtual Postulacione Postulacione { get; set; }
        public virtual Preguntas_Vacante Preguntas_Vacante { get; set; }
    }
}
