//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEgresados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios_Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios_Empresa()
        {
            this.Visualizaciones_CV = new HashSet<Visualizaciones_CV>();
        }
    
        public int id_usuario_empresa { get; set; }
        public int id_empresa { get; set; }
        public string nombre_usuario { get; set; }
        public string email { get; set; }
        public string nombre_completo { get; set; }
        public string cargo { get; set; }
        public string password_hash { get; set; }
        public string rol { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visualizaciones_CV> Visualizaciones_CV { get; set; }
    }
}
