//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEgresados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vacante()
        {
            this.Postulaciones = new HashSet<Postulacione>();
            this.Preguntas_Vacante = new HashSet<Preguntas_Vacante>();
        }
    
        public int id_vacante { get; set; }
        public int id_empresa { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public string requisitos { get; set; }
        public Nullable<decimal> salario_min { get; set; }
        public Nullable<decimal> salario_max { get; set; }
        public Nullable<bool> salario_confidencial { get; set; }
        public string modalidad { get; set; }
        public string tipo_contrato { get; set; }
        public string ubicacion { get; set; }
        public string area { get; set; }
        public Nullable<System.DateTime> fecha_publicacion { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
        public string estado { get; set; }
        public Nullable<int> creado_por { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Postulacione> Postulaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Preguntas_Vacante> Preguntas_Vacante { get; set; }
    }
}
