//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEgresados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visualizaciones_CV
    {
        public int id_visualizacion { get; set; }
        public int id_cv { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public Nullable<int> id_usuario_empresa { get; set; }
        public System.DateTime fecha_visualizacion { get; set; }
        public string ip_address { get; set; }
        public string navegador { get; set; }
        public string observaciones { get; set; }
    
        public virtual CVs_Egresados CVs_Egresados { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Usuarios_Empresa Usuarios_Empresa { get; set; }
    }
}
